### ISSUE TITLE
startup exception (javafx)

### ISSUE THREAD

**Issue by almibe** [almibe/library-weasel#115]
Exception in thread "JavaFX Application Thread" java.util.ConcurrentModificationException
        at java.util.AbstractList$Itr.checkForComodification(AbstractList.java:386)
        at java.util.AbstractList$Itr.next(AbstractList.java:355)
        at org.libraryweasel.developer.console.StartPageFactory$createNode$updateDisplay$1$1.run(StartPageFactory.kt:85)
        at com.sun.javafx.application.PlatformImpl.lambda$null$173(PlatformImpl.java:295)
        at java.security.AccessController.doPrivileged(Native Method)
        at com.sun.javafx.application.PlatformImpl.lambda$runLater$174(PlatformImpl.java:294)
        at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95)
        at com.sun.glass.ui.gtk.GtkApplication._runLoop(Native Method)
        at com.sun.glass.ui.gtk.GtkApplication.lambda$null$49(GtkApplication.java:139)
        at java.lang.Thread.run(Thread.java:748)

**Comment by almibe** [comment]
I've stopped using JavaFX so this isn't an issue anymore.
