### ISSUE TITLE
replace OrientDB with Xodus

### ISSUE THREAD

**Issue by almibe** [almibe/library-weasel#122]
Current startup errors

```
org.osgi.framework.BundleException: Unresolved constraint in bundle org.libraryweasel.library-weasel-developer-user [29]: Unable to resolve 29.0: missing requirement [29.0] osgi.wiring.package; (&(osgi.wiring.package=org.libraryweasel.auth.api)(version>=0.3.0)(!(version>=1.0.0))) [caused by: Unable to resolve 36.0: missing requirement [36.0] osgi.wiring.package; (&(osgi.wiring.package=jetbrains.exodus.entitystore)(version>=0.1.0)(!(version>=1.0.0))) [caused by: Unable to resolve 41.0: missing requirement [41.0] osgi.wiring.package; (osgi.wiring.package=com.sun.management)]]
        at org.apache.felix.framework.Felix.resolveBundleRevision(Felix.java:3980)
        at org.apache.felix.framework.Felix.startBundle(Felix.java:2043)
        at org.apache.felix.framework.BundleImpl.start(BundleImpl.java:976)
        at org.apache.felix.framework.BundleImpl.start(BundleImpl.java:963)
        at org.libraryweasel.LibraryWeaselMain.lambda$runStartTask$1(LibraryWeaselMain.java:40)
        at java.util.ArrayList.forEach(ArrayList.java:1249)
        at org.libraryweasel.LibraryWeaselMain.runStartTask(LibraryWeaselMain.java:38)
        at org.libraryweasel.LibraryWeaselMain.start(LibraryWeaselMain.java:19)
        at org.libraryweasel.LibraryWeaselMain.main(LibraryWeaselMain.java:30)
org.osgi.framework.BundleException: Unresolved constraint in bundle org.libraryweasel.library-weasel-developer-util [32]: Unable to resolve 32.0: missing requirement [32.0] osgi.wiring.package; (&(osgi.wiring.package=jetbrains.exodus.entitystore)(version>=0.1.0)(!(version>=1.0.0))) [caused by: Unable to resolve 41.0: missing requirement [41.0] osgi.wiring.package; (osgi.wiring.package=com.sun.management)]
        at org.apache.felix.framework.Felix.resolveBundleRevision(Felix.java:3980)
        at org.apache.felix.framework.Felix.startBundle(Felix.java:2043)
        at org.apache.felix.framework.BundleImpl.start(BundleImpl.java:976)
        at org.apache.felix.framework.BundleImpl.start(BundleImpl.java:963)
        at org.libraryweasel.LibraryWeaselMain.lambda$runStartTask$1(LibraryWeaselMain.java:40)
        at java.util.ArrayList.forEach(ArrayList.java:1249)
        at org.libraryweasel.LibraryWeaselMain.runStartTask(LibraryWeaselMain.java:38)
        at org.libraryweasel.LibraryWeaselMain.start(LibraryWeaselMain.java:19)
        at org.libraryweasel.LibraryWeaselMain.main(LibraryWeaselMain.java:30)
org.osgi.framework.BundleException: Unresolved constraint in bundle org.libraryweasel.library-weasel-auth [36]: Unable to resolve 36.0: missing requirement [36.0] osgi.wiring.package; (&(osgi.wiring.package=jetbrains.exodus.entitystore)(version>=0.1.0)(!(version>=1.0.0))) [caused by: Unable to resolve 41.0: missing requirement [41.0] osgi.wiring.package; (osgi.wiring.package=com.sun.management)]
        at org.apache.felix.framework.Felix.resolveBundleRevision(Felix.java:3980)
        at org.apache.felix.framework.Felix.startBundle(Felix.java:2043)
        at org.apache.felix.framework.BundleImpl.start(BundleImpl.java:976)
        at org.apache.felix.framework.BundleImpl.start(BundleImpl.java:963)
        at org.libraryweasel.LibraryWeaselMain.lambda$runStartTask$1(LibraryWeaselMain.java:40)
        at java.util.ArrayList.forEach(ArrayList.java:1249)
        at org.libraryweasel.LibraryWeaselMain.runStartTask(LibraryWeaselMain.java:38)
        at org.libraryweasel.LibraryWeaselMain.start(LibraryWeaselMain.java:19)
        at org.libraryweasel.LibraryWeaselMain.main(LibraryWeaselMain.java:30)
org.osgi.framework.BundleException: Unresolved constraint in bundle org.libraryweasel.library-weasel-xodus [41]: Unable to resolve 41.0: missing requirement [41.0] osgi.wiring.package; (osgi.wiring.package=com.sun.management)
        at org.apache.felix.framework.Felix.resolveBundleRevision(Felix.java:3980)
        at org.apache.felix.framework.Felix.startBundle(Felix.java:2043)
        at org.apache.felix.framework.BundleImpl.start(BundleImpl.java:976)
        at org.apache.felix.framework.BundleImpl.start(BundleImpl.java:963)
        at org.libraryweasel.LibraryWeaselMain.lambda$runStartTask$1(LibraryWeaselMain.java:40)
        at java.util.ArrayList.forEach(ArrayList.java:1249)
        at org.libraryweasel.LibraryWeaselMain.runStartTask(LibraryWeaselMain.java:38)
        at org.libraryweasel.LibraryWeaselMain.start(LibraryWeaselMain.java:19)
        at org.libraryweasel.LibraryWeaselMain.main(LibraryWeaselMain.java:30)
org.osgi.framework.BundleException: Unresolved constraint in bundle org.almibe.ligature-store [42]: Unable to resolve 42.0: missing requirement [42.0] osgi.wiring.package; (osgi.wiring.package=com.orientechnologies.orient.core.db)
        at org.apache.felix.framework.Felix.resolveBundleRevision(Felix.java:3980)
        at org.apache.felix.framework.Felix.startBundle(Felix.java:2043)
        at org.apache.felix.framework.BundleImpl.start(BundleImpl.java:976)
        at org.apache.felix.framework.BundleImpl.start(BundleImpl.java:963)
        at org.libraryweasel.LibraryWeaselMain.lambda$runStartTask$1(LibraryWeaselMain.java:40)
        at java.util.ArrayList.forEach(ArrayList.java:1249)
        at org.libraryweasel.LibraryWeaselMain.runStartTask(LibraryWeaselMain.java:38)
        at org.libraryweasel.LibraryWeaselMain.start(LibraryWeaselMain.java:19)
        at org.libraryweasel.LibraryWeaselMain.main(LibraryWeaselMain.java:30)
org.osgi.framework.BundleException: Unresolved constraint in bundle org.libraryweasel.library-weasel-ghissue-view [45]: Unable to resolve 45.0: missing requirement [45.0] osgi.wiring.package; (osgi.wiring.package=com.orientechnologies.orient.core.db)
        at org.apache.felix.framework.Felix.resolveBundleRevision(Felix.java:3980)
        at org.apache.felix.framework.Felix.startBundle(Felix.java:2043)
        at org.apache.felix.framework.BundleImpl.start(BundleImpl.java:976)
        at org.apache.felix.framework.BundleImpl.start(BundleImpl.java:963)
        at org.libraryweasel.LibraryWeaselMain.lambda$runStartTask$1(LibraryWeaselMain.java:40)
        at java.util.ArrayList.forEach(ArrayList.java:1249)
        at org.libraryweasel.LibraryWeaselMain.runStartTask(LibraryWeaselMain.java:38)
        at org.libraryweasel.LibraryWeaselMain.start(LibraryWeaselMain.java:19)
        at org.libraryweasel.LibraryWeaselMain.main(LibraryWeaselMain.java:30)

```

**Comment by almibe** [comment]
This is done except for a few plugins that aren't 100% complete anyway.
