### ISSUE TITLE
fix application lifecycle mess

### ISSUE THREAD

**Issue by almibe** [almibe/library-weasel#83]
## Issues
- [X] Copy pre-created database instead of initializing one via OrientDB's api (which takes 10 seconds to do.
- [x] Fix all startup and shutdown exceptions
- [x] Make sure application shuts down properly, right now it's hanging

```
Aug 10, 2016 1:10:37 AM io.netty.resolver.dns.DnsServerAddresses <clinit>
WARNING: Default DNS servers: [/8.8.8.8:53, /8.8.4.4:53] (Google Public DNS as a fallback)
Aug 10, 2016 1:10:38 AM com.orientechnologies.common.log.OLogManager log
INFO: OrientDB auto-config DISKCACHE=1,765MB (heap=1,765MB direct=1,765MB os=7,941MB), assuming maximum direct memory size equals to maximum JVM heap size
Aug 10, 2016 1:10:38 AM com.orientechnologies.common.log.OLogManager log
WARNING: MaxDirectMemorySize JVM option is not set or has invalid value, that may cause out of memory errors. Please set the -XX:MaxDirectMemorySize=7941m option when you start the JVM.
Aug 10, 2016 1:10:52 AM com.orientechnologies.common.log.OLogManager log
WARNING: $ANSI{green {db=orientdb}} Requested command 'create vertex type 'GHIssueRepo' as subclass of 'V'' must be executed outside active transaction: the transaction will be committed and reopen right after it. To avoid this behavior execute it outside a transaction
Aug 10, 2016 1:10:54 AM com.orientechnologies.common.log.OLogManager log
WARNING: $ANSI{green {db=orientdb}} Requested command 'create vertex type 'GHIssue' as subclass of 'V'' must be executed outside active transaction: the transaction will be committed and reopen right after it. To avoid this behavior execute it outside a transaction
Aug 10, 2016 1:11:13 AM com.orientechnologies.common.log.OLogManager log
INFO: Orient Engine is shutting down...
Aug 10, 2016 1:11:13 AM com.orientechnologies.common.log.OLogManager log
INFO: - shutdown storage: orientdb...
Aug 10, 2016 1:11:16 AM com.orientechnologies.common.log.OLogManager log
INFO: OrientDB Engine shutdown complete
Aug 10, 2016 1:11:16 AM io.netty.resolver.AddressResolverGroup close
WARNING: Failed to close a resolver:
java.lang.NoClassDefFoundError: io/netty/channel/AbstractChannelHandlerContext$13
	at io.netty.channel.AbstractChannelHandlerContext.close(AbstractChannelHandlerContext.java:596)
	at io.netty.channel.AbstractChannelHandlerContext.close(AbstractChannelHandlerContext.java:451)
	at io.netty.channel.DefaultChannelPipeline.close(DefaultChannelPipeline.java:943)
	at io.netty.channel.AbstractChannel.close(AbstractChannel.java:227)
	at io.vertx.core.dns.impl.fix.DnsNameResolver.close(DnsNameResolver.java:281)
	at io.vertx.core.impl.AddressResolver$1$1.close(AddressResolver.java:148)
	at io.netty.resolver.AddressResolverGroup.close(AddressResolverGroup.java:109)
	at io.vertx.core.impl.AddressResolver.close(AddressResolver.java:181)
	at io.vertx.core.impl.VertxImpl.lambda$close$8(VertxImpl.java:481)
	at io.vertx.core.impl.DeploymentManager.lambda$undeployAll$4(DeploymentManager.java:242)
	at io.vertx.core.impl.ContextImpl.lambda$wrapTask$3(ContextImpl.java:359)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:339)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:393)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:742)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.ClassNotFoundException: Unable to load class 'io.netty.channel.AbstractChannelHandlerContext$13' because the bundle wiring for io.netty.transport is no longer valid.
	at org.apache.felix.framework.BundleWiringImpl.findClassOrResourceByDelegation(BundleWiringImpl.java:1512)
	at org.apache.felix.framework.BundleWiringImpl.access$400(BundleWiringImpl.java:77)
	at org.apache.felix.framework.BundleWiringImpl$BundleClassLoader.loadClass(BundleWiringImpl.java:1988)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 15 more

Aug 10, 2016 1:11:16 AM io.vertx.core.impl.ContextImpl
SEVERE: Unhandled exception
java.lang.NoClassDefFoundError: io/netty/channel/group/ChannelMatchers
	at io.netty.channel.group.DefaultChannelGroup.close(DefaultChannelGroup.java:226)
	at io.vertx.core.http.impl.HttpServerImpl.actualClose(HttpServerImpl.java:506)
	at io.vertx.core.http.impl.HttpServerImpl.close(HttpServerImpl.java:420)
	at io.vertx.core.impl.VertxImpl.lambda$null$6(VertxImpl.java:504)
	at io.vertx.core.impl.VertxImpl.lambda$closeClusterManager$4(VertxImpl.java:462)
	at io.vertx.core.impl.ContextImpl.lambda$wrapTask$3(ContextImpl.java:359)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:339)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:393)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:742)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.ClassNotFoundException: Unable to load class 'io.netty.channel.group.ChannelMatchers' because the bundle wiring for io.netty.transport is no longer valid.
	at org.apache.felix.framework.BundleWiringImpl.findClassOrResourceByDelegation(BundleWiringImpl.java:1512)
	at org.apache.felix.framework.BundleWiringImpl.access$400(BundleWiringImpl.java:77)
	at org.apache.felix.framework.BundleWiringImpl$BundleClassLoader.loadClass(BundleWiringImpl.java:1988)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 10 more
```

**Comment by almibe** [comment]
Half of this is also from after closing.

**Comment by almibe** [comment]
Can I go back to just copying an empty database during the build?  Are OrientDB files tranferrable between linux and windows and macs?

**Comment by almibe** [comment]
The application also currently hangs after closing main window.

**Comment by almibe** [comment]
I'm now copying an new database on startup if there isn't one.  This is greatly speeding up startup time.  However there is still time for improvement.

**Comment by almibe** [comment]
I added code to make sure that vertx is closed before the stop method is left.  See LocalHttpServer class

**Comment by almibe** [comment]
Closing for now.  I removed the last checklist item since I created a specific ticket for it.
https://github.com/almibe/library-weasel-ghissue-view/issues/5
