### ISSUE TITLE
error on close

### ISSUE THREAD

**Issue by almibe** [almibe/library-weasel#85]
```
Aug 19, 2016 9:30:27 PM io.netty.util.ThreadDeathWatcher$Watcher notifyWatchees
WARNING: Thread death watcher task raised an exception:
java.lang.NoClassDefFoundError: io/netty/util/Recycler$WeakOrderQueue
	at io.netty.util.Recycler$DefaultHandle.recycle(Recycler.java:171)
	at io.netty.buffer.PoolThreadCache$MemoryRegionCache$Entry.recycle(PoolThreadCache.java:471)
	at io.netty.buffer.PoolThreadCache$MemoryRegionCache.freeEntry(PoolThreadCache.java:454)
	at io.netty.buffer.PoolThreadCache$MemoryRegionCache.free(PoolThreadCache.java:426)
	at io.netty.buffer.PoolThreadCache$MemoryRegionCache.free(PoolThreadCache.java:418)
	at io.netty.buffer.PoolThreadCache.free(PoolThreadCache.java:275)
	at io.netty.buffer.PoolThreadCache.free(PoolThreadCache.java:266)
	at io.netty.buffer.PoolThreadCache.free0(PoolThreadCache.java:239)
	at io.netty.buffer.PoolThreadCache.access$000(PoolThreadCache.java:38)
	at io.netty.buffer.PoolThreadCache$1.run(PoolThreadCache.java:64)
	at io.netty.util.ThreadDeathWatcher$Watcher.notifyWatchees(ThreadDeathWatcher.java:205)
	at io.netty.util.ThreadDeathWatcher$Watcher.run(ThreadDeathWatcher.java:140)
	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:145)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.ClassNotFoundException: Unable to load class 'io.netty.util.Recycler$WeakOrderQueue' because the bundle wiring for io.netty.common is no longer valid.
	at org.apache.felix.framework.BundleWiringImpl.findClassOrResourceByDelegation(BundleWiringImpl.java:1512)
	at org.apache.felix.framework.BundleWiringImpl.access$400(BundleWiringImpl.java:77)
	at org.apache.felix.framework.BundleWiringImpl$BundleClassLoader.loadClass(BundleWiringImpl.java:1988)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 14 more
```

**Comment by almibe** [comment]
Fixed
